### ISSUE TITLE
Down-Up interaction breaks the flow

### ISSUE THREAD

**Issue by Mangatome** [Mangatome/WeTookOutStephen#1]
The interaction should be shorter and more pleasant to perform.
The guide's animation should give feedback (be slightly different) when the mouse can be released.

**Comment by biotomas** [comment]
I would replace the down-up interaction with a hold interaction (hold until disappears). Some simple animation can be added, for example the sprite starts spinning with increasing speed (as the user holds) and then just disappears.

**Comment by Mangatome** [comment]
Fixed in 1da0d6f8dead0866df26c287d70228cf0545085c
