### ISSUE TITLE
Cleanup unused scenes and code

### ISSUE THREAD

**Issue by Mangatome** [Mangatome/WeTookOutStephen#5]
Remove from the project the unused scenes.
Rename scenes and code that were hastily named.
Make sure all assets (visuals and sounds) are used and can appear in the game.

**Comment by biotomas** [comment]
If we have unused visual assets I think we should rather start using them instead of removing.

**Comment by Mangatome** [comment]
Absolutely. I'll change the description.

**Comment by biotomas** [comment]
The girls might have visual assets that are not in the repository, we should add those too.

**Comment by Mangatome** [comment]
Yes, added as #7

**Comment by Mangatome** [comment]
Done.
